/// Flutter icons IconTopBar
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  IconTopBar
///      fonts:
///       - asset: fonts/IconTopBar.ttf
///
/// 
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
///
import 'package:flutter/widgets.dart';

class IconTopBar {
  IconTopBar._();

  static const _kFontFam = 'IconTopBar';
  static const String _kFontPkg = null;

  static const IconData all = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData burger = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData kebab = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pizza = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData keyboard_arrow_left = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData keyboard_arrow_down = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
